const dtvanSourceUrl = "https://www.dtvan.ca/wc/";
const downtown = "Downtown / Stadium District";

export const venueSeed = [
  {
    neighbourhood: downtown,
    name: "The Pearl",
    address: "881 Granville St, Vancouver, BC",
    latitude: 49.2799,
    longitude: -123.1216,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://thepearlvancouver.com/all-shows/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Live music venue",
    watchPartyDetails: "Free Brazil and Egypt viewing parties followed by ticketed after-parties with DJs, food, drinks, and dancing.",
  },
  {
    neighbourhood: downtown,
    name: "Lavantine Restaurant & Skybar",
    address: "833 W Pender St, Vancouver, BC",
    latitude: 49.2858701487727,
    longitude: -123.11635894473287,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://lavantine.ca/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Rooftop restaurant and bar",
    watchPartyDetails: "Exclusive rooftop match-day celebrations with live screenings, BBQ features, cocktails, and skyline views.",
  },
  {
    neighbourhood: downtown,
    name: "Bentall Centre",
    address: "Dunsmuir Patio, 1025 Dunsmuir St, Vancouver, BC",
    latitude: 49.28630944974664,
    longitude: -123.12060508716745,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://www.bentallcentre.com/events/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Outdoor public patio",
    watchPartyDetails: "The Pitchside Patio will show select matches on a big outdoor screen with drinks and lounge seating from June 11 to July 15.",
  },
  {
    neighbourhood: downtown,
    name: "Partee Putt Vancouver",
    address: "670 Smithe St, Vancouver, BC",
    latitude: 49.28012288356734,
    longitude: -123.12125550674747,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    reservationUrl: "https://www.parteeputt.com/vancouver/book-now",
    websiteUrl: "https://www.parteeputt.com/vancouver/book-now",
    sourceUrl: dtvanSourceUrl,
    venueType: "Mini golf and arcade bar",
    tvCount: 15,
    watchPartyDetails: "Watch the matches across 15 TVs, including one of the biggest screens in the city, alongside mini golf and arcade games.",
  },
  {
    neighbourhood: downtown,
    name: "BC Place",
    address: "777 Pacific Blvd, Vancouver, BC",
    latitude: 49.276684,
    longitude: -123.112404,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://www.bcplace.com/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Official FIFA World Cup stadium",
    watchPartyDetails: "Official host of the 2026 FIFA World Cup matches and Last Mile in Vancouver.",
  },
  {
    neighbourhood: downtown,
    name: "Cabana Nightclub",
    address: "1163 Granville St, Vancouver, BC",
    latitude: 49.27792968271,
    longitude: -123.12596426626789,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    reservationUrl: "https://www.eventbrite.com/cc/gameday-soccer-watch-parties-4840282",
    websiteUrl: "https://www.eventbrite.com/cc/gameday-soccer-watch-parties-4840282",
    sourceUrl: dtvanSourceUrl,
    venueType: "Nightclub",
    tvCount: 8,
    specials: "Drink specials, live DJs, and themed parties throughout the tournament.",
    watchPartyDetails: "All games will be shown on eight big-screen projectors.",
  },
  {
    neighbourhood: downtown,
    name: "Metropolitan Hotel + Diva at the Met",
    address: "645 Howe St, Vancouver, BC",
    latitude: 49.2839999766863,
    longitude: -123.1183234653152,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    reservationUrl: "https://metropolitan-hotel-vancouver.my.canva.site/fifa-world-cup/game-day-at-the-met",
    websiteUrl: "https://metropolitan-hotel-vancouver.my.canva.site/fifa-world-cup/game-day-at-the-met",
    sourceUrl: dtvanSourceUrl,
    venueType: "Hotel restaurant and private lounges",
    specials: "Globally inspired food and drink specials celebrating host nations.",
    watchPartyDetails: "Bookable live-match experiences range from private lounges to the Tai Pan Signature Game Day Suite.",
  },
  {
    neighbourhood: downtown,
    name: "Lucha Libre Barra & Mexican Restaurant",
    address: "722 Nelson St, Vancouver, BC",
    latitude: 49.27951778716147,
    longitude: -123.12347356257061,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://www.luchalibretacos.ca/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Restaurant and bar",
    specials: "Happy hour and Latin American match-day food and drink promotions.",
    watchPartyDetails: "Every match will be shown on all screens with sound on.",
  },
  {
    neighbourhood: downtown,
    name: "Earls Test Kitchen",
    address: "905 Hornby St, Vancouver, BC",
    latitude: 49.28163868361804,
    longitude: -123.12366690674706,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://earls.ca/locations/test-kitchen/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Restaurant and bar",
    watchPartyDetails: "A Match Day Headquarters setup with stadium energy and a view of the game from every seat.",
  },
  {
    neighbourhood: downtown,
    name: "The Mexican Antojitos y Cantina",
    address: "1049 Granville St, Vancouver, BC",
    latitude: 49.279013475315026,
    longitude: -123.12387672492261,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://www.themexican.ca/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Restaurant and cantina",
    watchPartyDetails: "Live soccer will be shown on TV in the cantina and patio.",
  },
  {
    neighbourhood: "Gastown / Waterfront",
    name: "Junction Public Market",
    address: "200 Granville St, Vancouver, BC",
    latitude: 49.28631846204578,
    longitude: -123.11268482844174,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://junctionpublicmarket.com/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Outdoor public market and licensed patio",
    watchPartyDetails: "Listed by Destination Vancouver as an official World Cup watch-party location.",
  },
  {
    neighbourhood: downtown,
    name: "The Pawn Shop YVR",
    address: "1117 Granville St, Vancouver, BC",
    latitude: 49.278031,
    longitude: -123.125074,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://thepawnshopyvr.com/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Taco bar",
    watchPartyDetails: "Matches will be shown across multiple TVs throughout the venue.",
  },
  {
    neighbourhood: downtown,
    name: "Dublin Calling",
    address: "900 Granville St, Vancouver, BC",
    latitude: 49.280122,
    longitude: -123.121512,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://www.dublincalling.com/vancouver/home",
    sourceUrl: dtvanSourceUrl,
    venueType: "Sports bar",
    tvCount: 15,
    watchPartyDetails: "Fifteen big-screen TVs and non-stop sports programming.",
  },
  {
    neighbourhood: downtown,
    name: "The Rec Room Vancouver",
    address: "855 Granville St, Vancouver, BC",
    latitude: 49.280972,
    longitude: -123.121039,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://www.therecroom.com/granville",
    sourceUrl: dtvanSourceUrl,
    venueType: "Entertainment venue and restaurant",
    watchPartyDetails: "World Cup matches will be shown live, with arcade games available after the final whistle.",
  },
  {
    neighbourhood: downtown,
    name: "Good Co. Granville",
    address: "965 Granville St, Vancouver, BC",
    latitude: 49.279783,
    longitude: -123.122826,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://goodcobars.com/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Bar and restaurant",
    watchPartyDetails: "The venue will become the International Football House and show all matches during 39 days of free community watch parties.",
  },
  {
    neighbourhood: downtown,
    name: "Shamrock Storehouse",
    address: "678 Nelson St, Vancouver, BC",
    latitude: 49.279015,
    longitude: -123.122858,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://www.shamrockstorehouse.com/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Irish pub",
    specials: "Michelob Ultra bucket deals, entertainment, music, and swag giveaways.",
    watchPartyDetails: "All matches will be shown both inside the bar and outside on a large pop-up patio.",
  },
  {
    neighbourhood: downtown,
    name: "Malones Taphouse",
    address: "608 W Pender St, Vancouver, BC",
    latitude: 49.283947,
    longitude: -123.11431,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://www.malones.bc.ca/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Sports bar and taphouse",
    specials: "Daily food and drink specials, happy hour, and game-day features.",
    watchPartyDetails: "Screens are visible from every seat and multiple matches can play at once.",
  },
  {
    neighbourhood: downtown,
    name: "Evolve Grooming",
    address: "811 Hornby St, Vancouver, BC",
    latitude: 49.2827,
    longitude: -123.1208,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    reservationUrl: "https://evolvegrooming.ca/",
    websiteUrl: "https://evolvegrooming.ca/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Barbershop",
    watchPartyDetails: "Clients can watch live matches on in-store screens during a haircut or beard service.",
  },
  {
    neighbourhood: downtown,
    name: "Library Square Pub",
    address: "300 W Georgia St, Vancouver, BC",
    latitude: 49.280085,
    longitude: -123.115346,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://www.librarysquarepub.com/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Pub and outdoor watch party",
    watchPartyDetails: "A downtown watch party with seating for 300 inside and 150 outside, plus outdoor screens, live music, and games.",
  },
  {
    neighbourhood: downtown,
    name: "Donnellan's Irish Pub",
    address: "1082 Granville St, Vancouver, BC",
    latitude: 49.278215,
    longitude: -123.124089,
    geocodingSourceUrl: dtvanSourceUrl,
    confirmedWorldCup: true,
    websiteUrl: "https://www.donnellansirishpub.com/",
    sourceUrl: dtvanSourceUrl,
    venueType: "Irish pub",
    specials: "Exclusive deals, free-jersey giveaways, and live music Thursday through Sunday.",
    watchPartyDetails: "All matches will be shown on big screens with themed decor.",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://www.donnellansirishpub.com/",
  },
  {
    neighbourhood: "Fraser / Riley Park",
    name: "Bells & Whistles",
    address: "3296 Fraser St, Vancouver, BC",
    latitude: 49.2512026,
    longitude: -123.0900737,
    geocodingSourceUrl: "https://www.openstreetmap.org/way/1250117947",
    confirmedWorldCup: true,
    websiteUrl: "https://www.bellsandwhistlesyvr.ca/",
    sourceUrl: "https://www.bellsandwhistlesyvr.ca/worldcup",
    menuUrl: "https://www.bellsandwhistlesyvr.ca/fraser/food",
    socialUrl: "https://www.instagram.com/bellsandwhistlesyvr/",
    venueType: "Beer hall / restaurant",
    watchPartyDetails: "The official venue World Cup page says Bells & Whistles will show all 2026 World Cup matches and offers group-stage table reservations.",
  },
  {
    neighbourhood: "Olympic Village / Mount Pleasant / Main",
    name: "Brewhall",
    address: "97 E 2nd Ave, Vancouver, BC",
    latitude: 49.2695303,
    longitude: -123.1036822,
    geocodingSourceUrl: "https://www.openstreetmap.org/way/318642215",
    confirmedWorldCup: true,
    websiteUrl: "https://brewhall.com/",
    sourceUrl: "https://brewhall.com/2026/05/11/fifa-world-cup-2026/",
    menuUrl: "https://brewhall.com/menu/",
    socialUrl: "https://www.instagram.com/brewhall/",
    venueType: "Social hall / restaurant",
    specials: "Michelob Ultra features and a limited-time brunch menu.",
    watchPartyDetails: "BREWHALL's official World Cup page invites guests to reserve match-day tables and watch on the big screen.",
  },
  {
    neighbourhood: "East Van / Hastings / PNE",
    name: "FIFA Fan Festival Vancouver at Hastings Park / PNE",
    address: "2901 E Hastings St, Vancouver, BC",
    latitude: 49.2844075,
    longitude: -123.0397731,
    geocodingSourceUrl: "https://www.openstreetmap.org/way/89353340",
    confirmedWorldCup: true,
    sourceUrl: "https://www.theguardian.com/football/2026/jun/13/socceroos-fans-feel-at-home-vancouver-australia-canada-world-cup",
    venueType: "Official FIFA Fan Festival",
    watchPartyDetails: "Vancouver's official FIFA Fan Festival is operating at Hastings Park.",
  },
  {
    neighbourhood: "Granville Island / False Creek",
    name: "Granville Island Watch Party",
    address: "Granville Island, Vancouver, BC",
    latitude: 49.270713,
    longitude: -123.1342858,
    geocodingSourceUrl: "https://www.openstreetmap.org/relation/11670779",
    confirmedWorldCup: true,
    websiteUrl: "https://granvilleisland.com/",
    sourceUrl: "https://www.instagram.com/granville_island/",
    latestPhotoUrl: "assets/granville-island-watch-party.png",
    latestPhotoSourceUrl: "https://www.instagram.com/granville_island/",
    latestPhotoSourceLabel: "Official Granville Island Instagram",
    socialUrl: "https://www.instagram.com/granville_island/",
    venueType: "Covered outdoor public watch party",
    watchPartyDetails: "Official Granville Island social content shows a covered outdoor viewing area with a large screen, rows of chairs, and tables.",
  },
  {
    neighbourhood: downtown,
    name: "Red Card Sports Bar",
    address: "560 Smithe St, Vancouver, BC",
    latitude: 49.2793791,
    longitude: -123.120222,
    geocodingSourceUrl: "https://www.openstreetmap.org/node/3940288768",
    confirmedWorldCup: true,
    websiteUrl: "https://www.redcardsportsbar.ca/",
    sourceUrl: "https://www.redcardsportsbar.ca/",
    latestPhotoUrl: "assets/red-card-sports-bar-interior.jpg",
    latestPhotoSourceUrl: "https://www.redcardsportsbar.ca/gallery",
    latestPhotoSourceLabel: "Official Red Card gallery",
    menuUrl: "https://www.redcardsportsbar.ca/food-menu",
    socialUrl: "https://www.instagram.com/redcardsportsbar/",
    venueType: "Sports bar",
    tvCount: 16,
    watchPartyDetails: "The official venue site lists current World Cup matches, 16 hi-def TVs, two 106-inch projectors, and 45+ sports channels.",
  },
  {
    neighbourhood: downtown,
    name: "Shark Club / Canada House by Coca-Cola",
    address: "180 W Georgia St, Vancouver, BC",
    latitude: 49.2790036,
    longitude: -123.1132909,
    geocodingSourceUrl: "https://www.openstreetmap.org/node/13689517365",
    confirmedWorldCup: true,
    websiteUrl: "https://www.sharkclub.com/location/vancouver/",
    sourceUrl: "https://www.sharkclub.com/canada-house-vancouver/",
    latestPhotoUrl: "assets/shark-club-canada-house-interior.jpg",
    latestPhotoSourceUrl: "https://www.sharkclub.com/location/vancouver/",
    latestPhotoSourceLabel: "Official Shark Club gallery",
    menuUrl: "https://www.sharkclub.com/our-menus/vancouver-menu/",
    venueType: "Sports bar / Canada House",
    watchPartyDetails: "Canada House will show every match wall-to-wall on big screens with sound on, plus prizes and giveaways throughout the tournament. The venue also highlights two 12 ft x 7 ft HDTV screens.",
  },
  {
    neighbourhood: "Kits / West Broadway",
    name: "Hynes' Irish Pub",
    address: "3468 W Broadway, Vancouver, BC",
    latitude: 49.2641472,
    longitude: -123.1812961,
    geocodingSourceUrl: "https://www.openstreetmap.org/node/13063706620",
    websiteUrl: "https://www.hynesirishpub.com/",
    menuUrl: "https://www.hynesirishpub.com/menu",
    socialUrl: "https://www.instagram.com/hynesirishpub",
    venueType: "Irish pub",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://www.hynesirishpub.com/",
  },
  {
    neighbourhood: "Commercial Drive",
    name: "Park Drive",
    address: "1815 Commercial Dr, Vancouver, BC",
    latitude: 49.2684155,
    longitude: -123.0698789,
    geocodingSourceUrl: "https://www.openstreetmap.org/node/1944641265",
    websiteUrl: "https://www.parkdrive.ca/",
    menuUrl: "https://www.parkdrive.ca/the-gemm",
    venueType: "Neighbourhood bar",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://www.parkdrive.ca/the-gemm",
  },
  {
    neighbourhood: "Main Street / Mount Pleasant",
    name: "Courtside Food & Drinks",
    address: "2415 Main St, Vancouver, BC",
    latitude: 49.2634122,
    longitude: -123.1011882,
    geocodingSourceUrl: "https://www.openstreetmap.org/node/7647500334",
    websiteUrl: "https://www.courtsideonmain.com/",
    menuUrl: "https://www.courtsideonmain.com/menu/drinks#scroll",
    socialUrl: "https://www.instagram.com/courtsidemain/",
    venueType: "Sports bar",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://www.courtsideonmain.com/menu/drinks#scroll",
  },
  {
    neighbourhood: "Yaletown / False Creek",
    name: "The Wicklow Pub",
    address: "610 Stamps Landing, Vancouver, BC",
    websiteUrl: "https://thewicklow.com/",
    menuUrl: "https://thewicklow.com/menus/",
    venueType: "Waterfront pub",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://thewicklow.com/menus/",
  },
  {
    neighbourhood: "Yaletown / False Creek",
    name: "Yaletown Brewing Company",
    address: "1111 Mainland St, Vancouver, BC",
    websiteUrl: "https://mjg.ca/yaletown-brewing-company/",
    menuUrl: "https://mjg.ca/yaletown-brewing-company/",
    venueType: "Brewpub",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://mjg.ca/yaletown-brewing-company/",
  },
  {
    neighbourhood: "Yaletown / False Creek",
    name: "Banter Room",
    address: "1039 Mainland St, Vancouver, BC",
    websiteUrl: "https://banterroom.com/",
    menuUrl: "https://banterroom.com/menus/",
    venueType: "Restaurant and bar",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://banterroom.com/menus/",
  },
  {
    neighbourhood: "Kits / West Broadway",
    name: "Darby's Public House",
    address: "2001 Macdonald St, Vancouver, BC",
    websiteUrl: "https://darbys.pub/",
    menuUrl: "https://darbys.pub/",
    venueType: "Neighbourhood pub",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://darbys.pub/",
  },
  {
    neighbourhood: "Kits / West Broadway",
    name: "The King's Head Public House",
    address: "1618 Yew St, Vancouver, BC",
    websiteUrl: "https://www.kingshead.ca/",
    menuUrl: "https://www.kingshead.ca/",
    venueType: "Neighbourhood pub",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://www.kingshead.ca/",
  },
  {
    neighbourhood: "Kits / West Broadway",
    name: "LOCAL Public Eatery Kitsilano",
    address: "2210 Cornwall Ave, Vancouver, BC",
    websiteUrl: "https://localpubliceatery.com/neighbourhoods/kitsilano/",
    menuUrl: "https://localpubliceatery.com/neighbourhoods/kitsilano/",
    venueType: "Public eatery",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://localpubliceatery.com/neighbourhoods/kitsilano/",
  },
  {
    neighbourhood: "Main Street / Mount Pleasant",
    name: "Hero's Welcome",
    address: "3917 Main St, Vancouver, BC",
    websiteUrl: "https://heros-welcome.com/",
    venueType: "Neighbourhood bar",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://heros-welcome.com/",
  },
  {
    neighbourhood: "Main Street / Mount Pleasant",
    name: "The Cascade Room",
    address: "2616 Main St, Vancouver, BC",
    websiteUrl: "https://www.thecascade.ca/",
    menuUrl: "https://www.thecascade.ca/",
    venueType: "Cocktail bar and restaurant",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://www.thecascade.ca/",
  },
  {
    neighbourhood: "Main Street / Mount Pleasant",
    name: "Portland Craft",
    address: "3835 Main St, Vancouver, BC",
    websiteUrl: "https://portlandcraft.com/",
    menuUrl: "https://portlandcraft.com/",
    venueType: "Craft beer bar",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://portlandcraft.com/",
  },
  {
    neighbourhood: "Olympic Village / Mount Pleasant / Main",
    name: "Mahony's Tavern False Creek",
    address: "601 Stamps Landing, Vancouver, BC",
    websiteUrl: "https://mahonystavern.com/",
    menuUrl: "https://mahonystavern.com/",
    venueType: "Irish tavern",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://mahonystavern.com/",
  },
  {
    neighbourhood: "Olympic Village / Mount Pleasant / Main",
    name: "Tap & Barrel Olympic Village",
    address: "1 Athletes Way, Vancouver, BC",
    websiteUrl: "https://tapandbarrel.com/location/olympic-village/",
    menuUrl: "https://tapandbarrel.com/location/olympic-village/",
    venueType: "Restaurant and taproom",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://tapandbarrel.com/location/olympic-village/",
  },
  {
    neighbourhood: "Olympic Village / Mount Pleasant / Main",
    name: "CRAFT Beer Market False Creek",
    address: "85 W 1st Ave, Vancouver, BC",
    websiteUrl: "https://www.craftbeermarket.ca/locations/vancouver-false-creek/",
    menuUrl: "https://www.craftbeermarket.ca/locations/vancouver-false-creek/",
    venueType: "Beer market",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://www.craftbeermarket.ca/locations/vancouver-false-creek/",
  },
  {
    neighbourhood: "Commercial Drive",
    name: "St. Augustine's",
    address: "2360 Commercial Dr, Vancouver, BC",
    websiteUrl: "https://staugustinesvancouver.com/",
    menuUrl: "https://staugustinesvancouver.com/",
    venueType: "Craft beer bar",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://staugustinesvancouver.com/",
  },
  {
    neighbourhood: "Commercial Drive",
    name: "The Charlatan",
    address: "1447 Commercial Dr, Vancouver, BC",
    websiteUrl: "https://www.thecharlatan.ca/",
    menuUrl: "https://www.thecharlatan.ca/",
    venueType: "Neighbourhood pub",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://www.thecharlatan.ca/",
  },
  {
    neighbourhood: "Commercial Drive",
    name: "Toby's Pub & Grill",
    address: "2733 Commercial Dr, Vancouver, BC",
    websiteUrl: "https://tobyspub.com/",
    menuUrl: "https://tobyspub.com/",
    venueType: "Neighbourhood pub",
    servesGuinnessTap: true,
    guinnessSourceUrl: "https://tobyspub.com/",
  },
];
